name: Build and Publish Docker Image

on:
  push:
    paths:
      - "release-versions/*"

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v2

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: Read Version file
        id: getversion
        run: echo "::set-output name=version::$(cat release-versions/wiki-js-version.txt)"

      - name: "Run publish docker script"
        run: ./publish-docker.sh ${{ steps.getversion.outputs.version }}

      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Push image to Docker Hub"
        run: ./push-docker.sh ${{ steps.getversion.outputs.version }} ${{ secrets.DOCKERHUB_USERNAME }}
